#!/usr/bin/env python3
# Copyright 2026 Roland Arsenault
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""
Encode a GeoJSON line layer into the explorer's compact coastline format.

Run through regenerate.sh; see README.md in this directory for the format
specification, the provenance of the committed artifact, and why the vendored
form is this rather than the GeoJSON itself.
"""

import argparse
import datetime
import json
import os


def parts(geometry):
    """
    Return every LineString part of a LineString/MultiLineString geometry.

    Any other geometry type contributes nothing.
    """
    if geometry['type'] == 'LineString':
        return [geometry['coordinates']]
    if geometry['type'] == 'MultiLineString':
        return geometry['coordinates']
    return []


def encode(collection):
    """
    Encode a GeoJSON feature collection as coastline records.

    Returns the record lines, the polyline count and the point count.
    """
    body = []
    n_points = 0
    n_lines = 0
    for feature in collection.get('features', []):
        for part in parts(feature.get('geometry') or {}):
            # Quantise to milli-degrees (~111 m of latitude), an order of
            # magnitude finer than the generalisation of the source dataset,
            # then drop the points the quantisation collapsed onto their
            # predecessor.
            quantised = []
            for lon, lat in part:
                point = (int(round(lat * 1000.0)), int(round(lon * 1000.0)))
                if quantised and quantised[-1] == point:
                    continue
                quantised.append(point)
            if len(quantised) < 2:
                continue
            n_lines += 1
            n_points += len(quantised)
            body.append('> %d %d' % quantised[0])
            previous = quantised[0]
            for point in quantised[1:]:
                body.append('%d %d' % (point[0] - previous[0], point[1] - previous[1]))
                previous = point
    return body, n_lines, n_points


def main():
    """Convert the GeoJSON named on the command line into a coastline file."""
    parser = argparse.ArgumentParser(description='Encode a coastline file.')
    parser.add_argument('--input', required=True, help='GeoJSON line layer')
    parser.add_argument('--output', required=True, help='coastline file to write')
    parser.add_argument('--source', required=True, help='source URL, for the header')
    parser.add_argument('--dataset', required=True, help='dataset name, for the header')
    parser.add_argument('--version', required=True, help='dataset version, for the header')
    args = parser.parse_args()

    with open(args.input) as handle:
        collection = json.load(handle)
    body, n_lines, n_points = encode(collection)

    header = [
        '# marine_perception_tools coastline v1 (milli-degree deltas; see README.md)',
        '# dataset: %s' % args.dataset,
        '# version: %s' % args.version,
        '# source: %s' % args.source,
        '# terms: public domain (Natural Earth)',
        '# retrieved: %s' % datetime.date.today().isoformat(),
        '# generated by encode_coastline.py from %s' % os.path.basename(args.input),
        '# polylines: %d  points: %d' % (n_lines, n_points),
    ]
    with open(args.output, 'w') as handle:
        handle.write('\n'.join(header + body) + '\n')


if __name__ == '__main__':
    main()
